apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws-cluster-piotr
spec:
  id: platform-ref-aws-cluster-piotr
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: platform-ref-aws-network-piotr
  writeConnectionSecretToRef:
    name: platform-ref-aws-cluster-piotr
